/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchCompanyRouteImport } from './routes/research.$company'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchCompanyRoute = ResearchCompanyRouteImport.update({
  id: '/$company',
  path: '/$company',
  getParentRoute: () => ResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/research': typeof ResearchRouteWithChildren
  '/research/$company': typeof ResearchCompanyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/research': typeof ResearchRouteWithChildren
  '/research/$company': typeof ResearchCompanyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/research': typeof ResearchRouteWithChildren
  '/research/$company': typeof ResearchCompanyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/research' | '/research/$company'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/research' | '/research/$company'
  id: '__root__' | '/' | '/research' | '/research/$company'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResearchRoute: typeof ResearchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$company': {
      id: '/research/$company'
      path: '/$company'
      fullPath: '/research/$company'
      preLoaderRoute: typeof ResearchCompanyRouteImport
      parentRoute: typeof ResearchRoute
    }
  }
}

interface ResearchRouteChildren {
  ResearchCompanyRoute: typeof ResearchCompanyRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchCompanyRoute: ResearchCompanyRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResearchRoute: ResearchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
